linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - exhaustive
    - noctx

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning
      - name: error-return
        severity: warning

run:
  timeout: 5m
  go: "1.22"
